# Generated by Django 5.0.1 on 2024-01-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('specifications', models.FileField(null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='nalogovaya',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('OKTMO', models.CharField(max_length=500, verbose_name='ОКТМО')),
                ('datetime', models.DateTimeField(verbose_name='ДатаЗач')),
                ('INNADB', models.CharField(max_length=500, verbose_name='ИННАДБ')),
                ('INNUL', models.CharField(max_length=500, verbose_name='ИННЮЛ')),
                ('KBK', models.CharField(max_length=500, verbose_name='КБК')),
                ('KPP', models.CharField(max_length=500, verbose_name='КПП')),
                ('KPPADB', models.CharField(max_length=500, verbose_name='КППАДБ')),
                ('NAIMPLAT', models.CharField(max_length=500, verbose_name='НАИМПЛАТ')),
                ('SUM', models.CharField(max_length=500, verbose_name='СУМЗАЧ')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300, verbose_name='Главный Заголовок')),
                ('headline2', models.CharField(blank=True, max_length=500, verbose_name='ПодЗаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
