# Generated by Django 4.2.9 on 2024-02-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_barguzinsky_bauntovsky_bichursky_dzidinsky'),
    ]

    operations = [
        migrations.DeleteModel(
            name='barguzinsky',
        ),
        migrations.DeleteModel(
            name='bauntovsky',
        ),
        migrations.DeleteModel(
            name='Bichursky',
        ),
        migrations.DeleteModel(
            name='Dzidinsky',
        ),
    ]
