# Generated by Django 4.2.9 on 2024-02-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_nalogovaya_oktmo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nalogovaya',
            name='OKTMO',
        ),
        migrations.AlterField(
            model_name='nalogovaya',
            name='oktmo_id',
            field=models.CharField(max_length=500, verbose_name='ОКТМО'),
        ),
    ]
