# Generated by Django 4.2.9 on 2024-02-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_nalogovaya_oktmo_alter_nalogovaya_oktmo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nalogovaya',
            old_name='oktmo_id',
            new_name='OKTMO',
        ),
    ]
